### ISSUE TITLE
Update ChangeDocGenerator for Liquibase 3.6.2

### ISSUE THREAD

**Issue by nniesen** [liquibase/liquibase.github.com#112]
Update ChangeDocGenerator for Liquibase 3.6.2.

**Comment by nniesen** [comment]
Pull request for generator updates: https://github.com/liquibase/liquibase.github.com/pull/113

**Comment by nniesen** [comment]
Should I include the generated files or do you run the generator and commit those?

**Comment by nniesen** [comment]
Pull request for gradle wrapper project to pull dependencies needed to update and run the generator: https://github.com/liquibase/liquibase.github.com/pull/114

**Comment by nniesen** [comment]
Pull request for regenerated 3.6.2 changes docs: https://github.com/liquibase/liquibase.github.com/pull/115

I realize I created a branch off a branch off a branch but I wasn't sure how to split out the pull requests and figured you could always take them all or cherry pick. Just hoping to get the websites "Changes ?Refactoring" doc updated to something recent.

**Comment by nniesen** [comment]
FYI, everything in PR #115 was generated from liquibase-core:3.6.2 and it's transitive dependencies. You should get identical results running the generator, with the #113 changes, and liquibase-core:3.6.2 and it's transitive dependencies in the #114 changes.

**Comment by nniesen** [comment]
Note: I did not remove the `_doc_generators/lib` directory. So instead of #114, you could still manually pull dependencies, build a classpath for compilation, build a classpath for execution, and run the generator.

**Comment by r2datical** [comment]
Thanks, @nniesen ! @nvoxland accepted a lot of these PR's.
