### ISSUE TITLE
onFail="CONTINUE" executes guarded change set instead of skipping it

### ISSUE THREAD

**Issue by buffin** [liquibase/liquibase.github.com#124]
Using liquibase-cdi version 3.6.2 
a precondition within a changeset that does not hold in conjunction with onFail="CONTINUE" does not work as expected.

Expected: "Skip over the change set. Execution of the change set will be attempted again on the next update. Continue with the change log." (see http://www.liquibase.org/documentation/preconditions.html)
I thought that CONTINUE should skip the "guarded" changeset and continue with the next one (if any) in the changelog - causing a "try again next time".
See also an old discussion in http://forum.liquibase.org/topic/preconditions-onfail-continue-onsqloutput-test-broken

Actual: It logs "Continuing past: db.changelog.xml::(changeset id) despite precondition failure due to onFail='CONTINUE' (and also the onFailMessage)
and executes the guarded changeset (and also sets EXECTYPE in DATABASECHANGELOG to EXECUTED.)

The same precondition in conjunction with onFail="MARK_RAN" works as expected (it does not execute changeset, it sets EXECTYPE in DATABASECHANGELOG to MARK_RAN).

**Comment by r2datical** [comment]
Hi, @buffin ! My apologies for the late response. Are you still having an issue?

**Comment by buffin** [comment]
Hi @r2datical, I will try to reproduce this in liquibase-cdi version 3.8.0 and get back to you in a couple of days.

**Comment by buffin** [comment]
Could not reproduce both in liquibase-cdi version 3.6.2 and version 3.8.0;
onFail="CONTINUE" works as expected.
