### ISSUE TITLE
Touched Sequences are reported as Unexpected

### ISSUE THREAD

**Issue by fabioluciano** [liquibase/liquibase.github.com#133]
Missing Sequence(s): NONE
Unexpected Sequence(s):
     seq_cadastro_template_email
     seq_formula
     seq_instrumento
     seq_regra_negocio
     seq_regra_negocio_tipo_tdc
     seq_status_analise
     seq_status_requerimento
     seq_tag_email
     seq_tipo_par_servico
     seq_tipo_parametro
     seq_tipo_serv_instrumento
     seq_tipo_servico
     seq_tipo_tdc
     seq_variavel_entrada
     sq_status_tramite

**Comment by r2datical** [comment]
Hi, @fabioluciano ! Doesn't that mean you have sequences in your target database that are not listed in the changelog? Thanks!
