### ISSUE TITLE
Can't excludeObjects when starting generateChangeLog starting version 3.6.0

### ISSUE THREAD

**Issue by SantaKrauja** [liquibase/liquibase.github.com#137]
When using org.liquibase:liquibase-core:3.5.5
commandLine argument `excludeObjects=databasechangelog` works as expected for `generateChangeLog `command

When using org.liquibase:liquibase-core:3.6.0 and using the same command- error  is thrown:
```
Errors:
  Unexpected command parameter: '--excludeObjects=databasechangelog'
```
Looks like that Amit Shah has the sme problem: https://liquibase.jira.com/browse/CORE-2847 (commented about the issue excluding objects)

**Comment by r2datical** [comment]
There is no longer a need to exclude databasechangelog table with generateChangeLog. Thanks!
