### ISSUE TITLE
No errors shown for not using camel case in the changelog

### ISSUE THREAD

**Issue by easteryard** [liquibase/liquibase.github.com#138]
When executing the databaseChangeLog no errors were shown in the console when I had typed **_changeset_** instead of **_changeSet_**, like it normally would if the indentation or other issues were met. The change set was just ignored.

The changelog is written in YAML.

**Comment by r2datical** [comment]
Hi, @easteryard ! Are you still having an issue? If so, would you mind submitting an issue here: https://liquibase.jira.com/projects/CORE/issues.
