### ISSUE TITLE
Create Index on postgres fails due to incorrect syntax

### ISSUE THREAD

**Issue by int-ahmed** [liquibase/liquibase.github.com#139]
PostgreSql states that the indexes should exist in the same schema as the table and therefore does not require the schema name to be included in the generated query.

When running 
```
<createIndex tableName="user" indexName="idx_login">
 <column name="login" type="string">
</createIndex>
```

**Expected outcome:**
`create index idx_login on table public.user(login)`

**Current outcome:**
`create public.index idx_login on table public.user(login)`

This causes postgreSql to throw a syntax error.

This was reported earlier as well, See https://liquibase.jira.com/browse/CORE-1119

**Comment by r2datical** [comment]
Thank you! CORE-1119 is closed now.
