### ISSUE TITLE
database not found

### ISSUE THREAD

**Issue by danishlyy** [liquibase/liquibase.github.com#165]
Database "D:/liquibase-3.8.0-bin/h2tutorial" not found, and IFEXISTS=true, so we cant auto-create it [90146-199] 90146/90146 (Help)

my liquibase.properties content as follows:
```
driver: org.h2.Driver
classpath: ./h2-1.4.199.jar
url: jdbc:h2:file:./h2tutorial
username: admin
password: password
changeLogFile: myChangeLog.xml
```
my category is ：
`D:\liquibase-3.8.0-bin`
 in this category,it contains a sql folder,a myChangeLog.xml ,a h2-1.4.199.jar and others are exacted from liquibase.tar

when I double click  h2.jar ,it will show a website ,I input the username,password into the website and jdbc url the same as myChangeLog.xml , click the test connection,it will show the above errors. my computer system is windows x64

**Comment by r2datical** [comment]
Hi, @danishlyy ! Are you still having issues? How can we help?
