### ISSUE TITLE
[CORE-3472] DbChangelog xsd file > 3.6 is not available

### ISSUE THREAD

**Issue by DanielFran** [liquibase/liquibase.github.com#169]
DbChangelog parameters xsd files version > 3.6 are not available throught link http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.?.xsd, the latest available is http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.6.xsd

From githug repo https://github.com/liquibase/liquibase/tree/master/liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelogit should be available at least:

    http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.7.xsd

    http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd

 

Trying to use XML changelog files with:
````xml
<?xml version="1.0" encoding="utf-8"?>
<databaseChangeLog
xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd">

…

</databaseChangeLog>
````

**Environment**
Spring version 5.1.9.RELEASE
Spring Boot version 2.1.7.RELEASE
Liquibase version 3.8.0

**Comment by r2datical** [comment]
Hi, @DanielFran . Looks like this was resolved. Thank you!
