### ISSUE TITLE
Looking at the root page, I don't understand what this is

### ISSUE THREAD

**Issue by aes** [liquibase/liquibase.github.com#204]
## Expected Behavior
I expect to read 5-30 words and understand roughly what problem is being addressed. (Note that I don't need to understand or even get a hint of what solution you propose)

## Actual Behavior
I'm asked to choose between a community and a "Pro" version. (sort of nice, there being a community version is one of my strong preferences)

## Steps to Reproduce the Problem

  1. gargle "liquibase"
  1. visit first non-garbage link (actual first)
  1. confuse

## Suggestion
Perhaps a few words, such as "Database schema management" or similar*, could be placed prominently on the root page?

* Perhaps I still haven't understood what your project is for.

**Comment by r2datical** [comment]
This is my favorite issue EVER. We're on it.

**Comment by r2datical** [comment]
Anders, what do you think now? We have updated site to make it more clear what problem Liquibase solves. Do you agree?

**Comment by aes** [comment]
Yep, I know some of those words. Works for me™.

**Comment by r2liquibase** [comment]
Thanks!
