### ISSUE TITLE
Passing changelog params in CLI doesn't override liquibase.properties params

### ISSUE THREAD

**Issue by doublebarrelbuckshot** [liquibase/liquibase.github.com#314]
## Expected Behavior
When I pass a parameter value in the CLI (dxxx) that also exists in the liquibase.properties file (parameter.xxx) then I expect the value passed in the CLI to take precedence over the one in the liquibase.properties file

## Actual Behavior
If the variable is defined in liquibase.properties and is also passed in the CLI, the value resolves to that which is liquibase.properties. If the variable is NOT defined in liquibase.properties, and is passed in the CLI, it resolves to the CLI passed value.

The documentation clearly says:
```
If a parameter is specified in both the properties file and the command line, the command line value will override the value in the file.
```

## Steps to Reproduce the Problem
liquibase.properties file:
```
# other standard properties here, such as driver/url/username/password...
parameter.akey: original
```

changelog 001.create-table.sql:
```
--liquibase formatted sql
CREATE TABLE toto(
  "${akey}" SERIAL
);
```

command line:
```
$ liquibase --changeLogFile=001.create-table.sql update -Dakey=updated
```

Result from "SELECT * FROM toto;"
```
 original 
----------
(0 rows)
```

==> The column name should be "updated" and not "original"

## Specifications (if applicable)

  - Version: 3.8.2 Community
  - Platform: Installed/run on a docker image on Alpine 3

**Comment by SteveDonie** [comment]
Thanks for raising this issue and writing up a good quality bug report. We don't typically track product issues in this repository (this should be just for documentation issues), so I have copied it into https://liquibase.jira.com/browse/CORE-3545

The team is currently working on migrating from Jira to Github issues, and when we do those will be tracked in the main Liquibase repository at https://github.com/liquibase/liquibase
