### ISSUE TITLE
Changelog parameters cannot be overridden in the parameters block in Formatted SQL

### ISSUE THREAD

**Issue by doublebarrelbuckshot** [liquibase/liquibase.github.com#315]
## Expected Behavior
The documentation says that we can configure change log parameters in the DatabaseChangeLog file itself. 

## Actual Behavior
There is no documentation on how to do this for Formatted SQL and all attempts to make this work have failed for me.

## Steps to Reproduce the Problem
Scenario 1: property found in liquibase.properties file and not overridden in changelog:

liquibase.properties file:
```
# other standard properties such as driver/username/password, etc...
parameter.akey: original
```

changelog file: 
```
--liquibase formatted sql
--changeset someuername:1
CREATE TABLE toto(
  "${akey}" SERIAL
);
```

result from "SELECT * FROM toto":
```
 original 
----------
(0 rows)
```
==> Good, this means that it the variable "akey" was found in liquibase.properties and resolved. This is the control situation.

Scenario 2: property found in liquibase.properties file and IS overridden in changelog

liquibase.properties file:
```
# other standard properties such as driver/username/password, etc...
parameter.akey: original
```

changelog file: 
```
--liquibase formatted sql
--changeset someuername:1
--property name:akey value:updated
CREATE TABLE toto(
  "${akey}" SERIAL
);
```

result from "SELECT * FROM toto":
```
 original 
----------
(0 rows)
```
==> doesn't care about the --property tag. perhaps its formatted wrong? I tried several variations with no success. There is no documentation on how to achieve this within formatted sql

Scenario 3: property NOT found in liquibase.properties file and IS defined in changelog file:

liquibase.properties file:
```
# only standard properties such as driver/username/password, etc...
```

changelog file: 
```
--liquibase formatted sql
--changeset someuername:1
--property name:anotherKey value:updated
CREATE TABLE toto(
  "${anotherKey}" SERIAL
);
```

result from "SELECT * FROM toto":
```
 ${anotherkey}
----------
(0 rows)
```
==> No replacement, takes literal value

## Specifications (if applicable)

  - Version: Liquibase Community 3.8.2 
  - Platform: Running inside Docker image on Alpine 3
  - Subsystem:

**Comment by SteveDonie** [comment]
Thanks for raising this issue and writing up a good quality bug report. We don't typically track product issues in this repository (this should be just for documentation issues), so I have copied it into https://liquibase.jira.com/browse/CORE-3544
The team is currently working on migrating from Jira to Github issues, and when we do those will be tracked in the main Liquibase repository at https://github.com/liquibase/liquibase
