### ISSUE TITLE
I am not able to use xInclude in liquibase xml changelog!!

### ISSUE THREAD

**Issue by Umartahir93** [liquibase/liquibase.github.com#363]
I am trying to include another xml file which is a fragement of XML file into my changelog. Whenever I execute my changelog in liquibase it gets executed successfully (without any parsing error) but no table is created in the database.

I am not sure we can use xInclude in liquibsae, but I think it should be possible as we are using xml underneath in liquibase. Plus I coulndt find any example of xinclude in liquibase and in offical documentation.

**Changelog.xml**

    <?xml version="1.0" encoding="UTF-8"?>
    <databaseChangeLog
    	xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
    	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    	xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
                          http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd"
                           xmlns:xi="http://www.w3c.org/2001/Xinclude">
    
    	<changeSet id="id-1234"
    		author="umarTahir">
    
    		<comment>creates table: employee</comment>
    		<xi:include
    			href="employee.xml" parse="xml"
             xpointer="title"/>
    
    		<rollback>
    			<dropTable schemaName="employee_test" tableName="employee" />
    		</rollback>
    	</changeSet>
    
    </databaseChangeLog>

**employee.xml**

    <createTable tableName="employee" xml:id="title">
    	<column name="employee_id" type="UUID">
    		<constraints primaryKey="true"
    			primaryKeyName="employee_pkey" />
    	</column>
    	<column name="first_name" type="TEXT" />
    	<column name="middle_name" type="TEXT" />
    	<column name="last_name" type="TEXT" />
    	<column name="email" type="TEXT" />
    	<column name="n_created_by" type="TEXT" />
    	<column name="n_created" type="TIMESTAMP WITHOUT TIME ZONE" />
    	<column name="n_last_modified_by" type="TEXT" />
    	<column name="n_last_modified"
    		type="TIMESTAMP WITHOUT TIME ZONE" />
    </createTable>

**Comment by SteveDonie** [comment]
Liquibase does not support xinclude. There are other mechanisms for including 'sub-changelogs' into a master changelog - see the <include> page in the documentation. https://www.liquibase.org/documentation/include.html

Here is a quote from that page explaining why Liquibase doesn't support xInclude:

> The reason to use the <include> tag rather than using XML’s built-in include functionality is that with the built-in functionality the parser sees just one big XML document. We uniquely identify each change with the id, the author, and the file name so you only have to ensure that the id/author combinations are unique within each file, not across all change logs.
