### ISSUE TITLE
Please fix drop column docs

### ISSUE THREAD

**Issue by sixcorners** [liquibase/liquibase.github.com#365]
https://www.liquibase.org/documentation/changes/drop_column.html
The example shows columnName="id" but the generated sql doesn't look like it did anything with that information.
Why are there two ways to specify column names?
Also it says that DB2 is supported but also that _DB2_ is not supported. That's confusing.

**Comment by sixcorners** [comment]
I would send a pull request but I don't know which way to specify column names is right. I also don't know if this is supported in DB2.

**Comment by SteveDonie** [comment]
Thanks for noticing! I'll take a look at that and get it updated soon.

**Comment by SteveDonie** [comment]
By the way, the DB2 being supported and NOT supported at the same time is for DB2 on Linux, Unix, Windows vs DB2 on zOS. That will require a change in the code that generates the docs from the code.

**Comment by SteveDonie** [comment]
I have pushed changes to address this to staging, which gets published to http://staging.liquibase.org/ 

The changes will get merged to master and published to the main site within the next day or so.
