### ISSUE TITLE
Catalog name is incorrectly uppercased for MariaDB

### ISSUE THREAD

**Issue by Mahoney** [liquibase/liquibase.github.com#38]
Hi,

We have an issue upgrading from 3.0.4 to 3.2.0*.

Using MariaDB 5.5, we have the DATABASECHANGELOG & DATABASECHANGELOGLOCK tables in a custom catalog with a lowercase name.

CatalogAndSchema.standardize upper cases the catalog name, resulting in java.sql.DatabaseMetaData.getTables returning an empty ResultSet, so liquibase incorrectly concludes it needs to create the tables & falls over when the DB rejects the create table command.

Connecting using mysql-connector-java 5.1.29.
- we are upgrading in the hope of using the Yaml config with preconditions & onFail=MARK_RAN, which doesn't work for us in versions prior to 3.2.0

**Comment by r2datical** [comment]
Unable to reproduce. Thanks for submitting!
