### ISSUE TITLE
@UniqueConstraint is giving null pointer exception

### ISSUE THREAD

**Issue by svennela** [liquibase/liquibase.github.com#51]
Hi,

I am running mvn pulgin to generate database log for jpa. I am getting null pointer exception when i run below command.  

mvn compile liquibase:diff

@Table(name = "T_USERRELEATION",uniqueConstraints = @UniqueConstraint(columnNames = { "FROM_USER_ID", "TO_USER_ID" }))

 @JoinColumn(name = "FROM_USER_ID", nullable = false)
    @NotNull
    private User fromUser; // (userId)

```
@JoinColumn(name = "TO_USER_ID", nullable = false)
@NotNull
private User toUser; // (userId)
```

**Comment by r2datical** [comment]
Hi, @svennela . My apologies for the late reply. Is this still an issue? Please reopen if it is. Thanks!
