### ISSUE TITLE
<constraints primaryKey="true" /> Does not work for informix with 3.3.3

### ISSUE THREAD

**Issue by ashishcoolbhargava** [liquibase/liquibase.github.com#58]
we have migrated from liquibase 2.0.3 to 3.3.3.
initially we were using to add the primary key

![capture1](https://cloud.githubusercontent.com/assets/10347759/8079621/79e82202-0f83-11e5-8311-d7235909b8e6.PNG)

But this does not work with Informix database after upgradation.

we need to use like 

![capture2](https://cloud.githubusercontent.com/assets/10347759/8079650/af5b07f6-0f83-11e5-9252-26f281b0834d.PNG)

which is costing us to change in each and every file.
Can we have something here.

Thanks

**Comment by r2datical** [comment]
Hi, @ashishcoolbhargava ! My apologies for the late reply. Is this still an issue? If so, please reopen. Thanks!
