### ISSUE TITLE
Password Parameter deletes the last character if it is a symbol when passed in liquibase.bat file

### ISSUE THREAD

**Issue by twenzel** [liquibase/liquibase.github.com#62]
This is a copy from https://liquibase.jira.com/browse/CORE-2250.

When the password parameter is passed via liquibase.bat file, if the last character in the password parameter is ! (an exclamation mark) or any character if it is symbol {@,#,$,%,^,&,*,(,)) , it gets deleted when passed to the liquibase.integration.commandline.Main method via liquibase,bat file.
So before the password parameter is passed to liquibase.jar, the bat file deletes the '!' if it is in the end.

**Comment by r2datical** [comment]
Thanks, @twenzel ! This was resolved in 4.0.0.
