### ISSUE TITLE
Missing pages and styles on liquibase website

### ISSUE THREAD

**Issue by m-radzikowski** [liquibase/liquibase.github.com#66]
Hey,
not sure if this is correct place to report this, but main liquibase page is not working correctly. For example
- http://www.liquibase.org/documentation/index.html
- http://www.liquibase.org/blog/
- http://www.liquibase.org/documentation/changes/index.html

are not working at all or don't have css/js.

On the other hand some of them are ok, like http://www.liquibase.org/documentation/xml_format.html

Difference seems to be in paths to assets - correct ones have

``` html
<link rel="stylesheet" href="../css/vendor/jquery-ui/jquery-ui.min.css">
```

and incorrect

``` html
<link rel="stylesheet" href="./css/vendor/jquery-ui/jquery-ui.min.css">
```

and so on.

**Comment by r2datical** [comment]
This appears to be resolved. Thank you!!!
