### ISSUE TITLE
custom change configuration support

### ISSUE THREAD

**Issue by jwaterloo** [liquibase/liquibase.github.com#67]
How doe one create a custom change that has the same level of configuration as the provided changes. For instance yours can be configured in XML, JSON and YAML. Secondly you can set complex properties as in the case of the columns elements in the loaddata and loaddataupdate but current custom changes are a second class citizen due to the param element.
Ex. <param name="id" value="2" />
How does one set arrays, maps  and list of typed objects which themselves can have more nesting.
For instance I may want to create the following:
<myLoadData csfFile="">
  <column columnconfigattribute></column>
  <column></column>
  <column></column>
</myLoadData

**Comment by r2datical** [comment]
Hi, @jwaterloo! Sorry for the delayed response!

Any thing that is not supported in Liquibase, such as arrays, maps, etc. can be created with an SQL file. You can have Liquibase execute the SQL file as part of it's deployment. Please see here for more information: http://www.liquibase.org/documentation/changes/sql_file.html.

Thanks!
