### ISSUE TITLE
Documentation for DEPLOYMENT_ID

### ISSUE THREAD

**Issue by suguiura** [liquibase/liquibase.github.com#75]
Since [v3.5.0](http://www.liquibase.org/2016/04/liquibase-3-5-0-released.html), liquibase produces a DATABASECHANGELOG.DEPLOYMENT_ID column:

> [CORE-2657] - Add new DATABASECHANGELOG.DEPLOYMENT_ID column to track changeSets deployed together

However, [`documentation/databasechangelog_table.md`](https://github.com/liquibase/liquibase.github.com/blob/master/documentation/databasechangelog_table.md) lacks update as can be seen in [the documentation page](http://www.liquibase.org/documentation/databasechangelog_table.html).

**Comment by Yogeshwar235** [comment]
Also CONTEXTS and LABELS columns are not updated in documentation

> Changes in version 3.4.0 (2015.06.24)
> - [CORE-2308] - Track changeSet contexts and labels in databasechangelog table

**Comment by r2datical** [comment]
Fixed!
