### ISSUE TITLE
Difference between value and defaultValue for column?

### ISSUE THREAD

**Issue by fredva** [liquibase/liquibase.github.com#79]
I am having trouble understanding the difference between `value` and `defaultValue` for [`column`](https://github.com/liquibase/liquibase.github.com/blob/master/documentation/column.md).

For instance, when adding a new, not nullable, column to a table, which of these should be used to set a value for all existing rows? 

What effect does `defaultValue` have that `value` does not?

I'm more than happy to update the documentation in a PR if I get a brief description of the differences as an answer to this issue.

**Comment by vitorreis** [comment]
I also have this doubt

**Comment by oleg-astakhov** [comment]
> For instance, when adding a new, not nullable, column to a table, which of these should be used to set a value for all existing rows?

**value**

> What effect does `defaultValue` have that `value` does not?

from documentation:

> Setting the "defaultValue" attribute will specify a default value for the column. Setting the "value" attribute will set all rows existing to the specified value without modifying the column default.
https://www.liquibase.org/documentation/changes/add_column.html

But yes, kind of in the wrong place since these are `column` attributes, not `addColumn`'s . The way it's written for `addColumn` is clearer than in the description of `column` tag.

**Comment by r2datical** [comment]
Great points and thank you for pointing this out. I've updated column.md to reflect the better description in add_column.md. Thanks!
