### ISSUE TITLE
Invalid SSL certificate on liquibase.org

### ISSUE THREAD

**Issue by fgreinus** [liquibase/liquibase.github.com#80]
Hey there,

just wanted to say, that https://www.liquibase.org/ shows an invalid SSL certificate. It's signed for github.com and all wildcards.

Maybe you find a way to fix this, as it looks suspicious for a new user... or just redirect from https->http.

Have a nice day.

**Comment by r2datical** [comment]
Thank you for the heads up! That was resolved awhile back and we neglected to close this issue. Thank you again!!!
